apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-node
spec:
  type: NodePort 
  selector:
    app: {{ $.Chart.Name }}
  ports:
    - port: 25565 
      name: mc
      nodePort: 32767
      targetPort: 25565
    - port: 25575 
      name: rcon
      nodePort: 32766
      targetPort: 25575